language : cpp
os :
    - linux
    - osx
script :
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./tests
compiler :
    - clang
    - gcc
notifications:
    slack: intech-sudparis:o8dpjkPWxJHduwjMye4pjPeF
    on_success: change
    on_failure: always
    email : false
